<?php

namespace core\ch3;

#define('__ROOT__', dirname(dirname(__FILE__)));
define('__ROOT__', dirname(dirname(__FILE__)));

require_once(__ROOT__."/core/ApplicationCore.php");


class Application extends \core\ApplicationCore
{
    # Init ----------------------------------------------------------------

    public function __construct()
    {
        parent::__construct();

        self::$_title = "Zandstra - Chapter 3";
        self::$_module = "Simple Objects (Chapter 3)";
    }

    # Run Engine ----------------------------------------------------------------

    public function Exec()
    {
        parent::Exec(); // TODO: Change the autogenerated stub

        $this->dynamicProperties();
    }

    # Examples ----------------------------------------------------------------

    public function dynamicProperties()
    {
        self::writeHeader("Dynamic Properties", 5);

        $cls = new class() {
          public $name = "Test";
          public $value = 0xff0a233;

          public function __toString(): string
          {
              $cls = print_r($this, true);
              return "$cls";
          }

          public function writeData()
          {
              echo htmlentities( $this->__toString() );
          }
        };

        $cls->dynamicProperty = new \DateTime();

        $cls->writeData();

        self::writeHeader("Class fields iteration");

        self::writeData($cls);

        $pdt = function(\DateTime $dt) { return $dt->format("d.m.Y H:i:s"); };

        foreach ( $cls as $k => $v )
        {
            if( is_object($v) )
            {
                self::writeLine($k."=>".$pdt($v));
            }
            else self::writeLine("$k => $v");
        }
    }


}